apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: adonis-role
rules:
  - apiGroups: ["", "apps"] # "" indicates the core API group
    resources: ["pods", "deployments"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps"]
    verbs: ["get", "watch", "list", "patch", "delete"]
